name: Load SQL data to PostgreSQL

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'sql/*.sql'

jobs:
  load-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem

    - name: Copy SQL files to EC2
      run: |
        scp -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no sql/*.sql \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

    - name: Execute SQL files in PostgreSQL container
      run: |
        ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker cp /tmp/init.sql postgresql-dev:/tmp/init.sql && \
           docker cp /tmp/data.sql postgresql-dev:/tmp/data.sql && \
           docker exec postgresql-dev psql -U ${{ secrets.POSTGRES_USER }} \
           -d ${{ secrets.POSTGRES_DB }} -f /tmp/init.sql && \
           docker exec postgresql-dev psql -U ${{ secrets.POSTGRES_USER }} \
           -d ${{ secrets.POSTGRES_DB }} -f /tmp/data.sql"