name: Load Data into PostgreSQL

on:
  workflow_dispatch: # Permite ejecución manual

jobs:
  load-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Clona el repo en el runner

    - name: Configurar SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }} # Clave privada desde Secrets
        known_hosts: "fake" # Ignora verificación de host (para pruebas)

    - name: Copiar SQL a EC2
      run: |
        # Copia los archivos .sql a la instancia EC2
        scp -o StrictHostKeyChecking=no -r ./sql ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

    - name: Ejecutar SQL en PostgreSQL
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        # Copia cada archivo SQL al contenedor y ejecútalo
        for sql_file in /home/$USER/sql/*.sql; do
          filename=$(basename "$sql_file")
          echo "Copiando $filename al contenedor..."
          docker cp "$sql_file" postgresql-dev:/tmp/"$filename"
          echo "Ejecutando $filename..."
          docker exec postgresql-dev psql \
            -U $POSTGRES_USER \
            -d $POSTGRES_DB \
            -f /tmp/"$filename"
        done
        echo "¡Datos cargados exitosamente!"
        EOF
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}